<?php
function News_menu() {
    $items = array();
    $items['News'] = array(
        'title' => 'The Latest News',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('source_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['result'] = array(
        'title' => 'Result',
        'page callback' => 'get_news',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function source_form(){
    $form['source'] = array(
        '#title'=>'Get the latest news',
        '#description'=>'pick a news source',
        '#type'=>'radios',
        '#options'=>array(
            t('associated-press'),
            t('bbc-news'),
            t('business-insider'),
        ),
        '#required'=>TRUE,
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'submit',
  );
  return $form;
}

function source_form_submit($form, &$form_state){
    $source = $form_state['values']['source'];
    $source_name = '';
    switch($source){
        case 0:
            $source_name = 'associated-press';
            break;
        case 1:
            $source_name = 'bbc-news';
            break;
        case 2:
            $source_name = 'business-insider';
            break;
        default:
            $source_name = 'error';
    }
    $_SESSION['source']=$source_name;
    $form_state['redirect']='result';
}

function get_news() {
    $source=$_SESSION['source'];
    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_RETURNTRANSFER => 1,
        CURLOPT_URL => 'https://newsapi.org/v1/articles?source='.$source.'&sortBy=latest&apiKey=ccd4623de5dd47dd9c48798e310b4e34',
        CURLOPT_USERAGENT => 'KojiKodes'
    ));
    $articles = curl_exec($curl);
    curl_close($curl);


    $stuff = json_decode($articles);
    $random_number = mt_rand(0,count($stuff->articles));
    echo '<pre>';
    var_dump($stuff->articles[$random_number]);
    var_dump($random_number);
    echo '</pre>';

    $article_array = [];
    $title = $stuff->articles[$random_number]->title;
    $author = $stuff->articles[$random_number]->author;
    $description = $stuff->articles[$random_number]->description;
    $url = $stuff->articles[$random_number]->url;
    $urlToImage = $stuff->articles[$random_number]->urlToImage;
    $publishedAt = $stuff->articles[$random_number]->publishedAt;

    return '
        <h2>'. $title . '</h2>
        <p>'. $description .'</p>
        <img src="'.$urlToImage.'"><br>
        <a href="'. $url .'">Read More</a>
    ';

}

function show_news() {
    return 'Hello';
}
