<?php
function News_menu() {
    $items = array();
    $items['News'] = array(
        'title' => 'The Latest News',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('source_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['result'] = array(
        'title' => 'Result',
        'page callback' => 'get_news',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function source_form(){
    $form['source'] = array(
        '#title'=>'Get the latest news',
        '#description'=>'pick a news source',
        '#type'=>'radios',
        '#options'=>array(
            t('MTV News'),
            t('daily-mail'),
            t('business-insider'),
        ),
        '#required'=>TRUE,
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'submit',
  );
  return $form;
}

function source_form_submit($form, &$form_state){
    $source = $form_state['values']['source'];
    $source_name = '';
    switch($source){
        case 0:
            $source_name = 'mtv-news';
            break;
        case 1:
            $source_name = 'daily-mail';
            break;
        case 2:
            $source_name = 'business-insider';
            break;
        default:
            $source_name = 'error';
    }
    $_SESSION['source']=$source_name;
    $form_state['redirect']='result';
}

function get_news() {
    $source=$_SESSION['source'];
    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_RETURNTRANSFER => 1,
        CURLOPT_URL => 'https://newsapi.org/v1/articles?source='.$source.'&sortBy=latest&apiKey=ccd4623de5dd47dd9c48798e310b4e34',
        CURLOPT_USERAGENT => 'KojiKodes'
    ));
    $articles = curl_exec($curl);
    curl_close($curl);
    $stuff = json_decode($articles);
    if(isset($stuff->articles[0])){
        $random_number = mt_rand(0,count($stuff->articles));
        $random_article = $stuff->articles[$random_number];
        echo '<pre>';
        var_dump($stuff->articles[$random_number]);
        var_dump($random_number);
        echo '</pre>';

        $title = $random_article->title;
        $author = $random_article->author;
        $description = $random_article->description;
        $url = $random_article->url;
        $urlToImage = $random_article->urlToImage;
        $publishedAt = $random_article->publishedAt;

        ////Create NODE
        $node = new stdClass();
        $node->title = $title;
        $node->type = 'news_article';
        node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
        $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
        $node->status = 1; //(1 or 0): published or not
        $node->promote = 1; //(1 or 0): promoted to front page
        $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write

        $node->field_author['und'][0]['value'] = $author;
        $node->field_url['und'][0]['value'] = $url;
        $node->field_image_url['und'][0]['value'] = $urlToImage;
        $node->field_published_at['und'][0]['value'] = $publishedAt;
        $node->field_source['und'][0]['value'] = $source;
        $node = node_submit($node);
        node_save($node);


        return '
        <h2>'. $title . '</h2>
        <p>'. $description .'</p>
        <img src="'.$urlToImage.'"><br>
        <a href="'. $url .'">Read More</a>
        ';
    }
    return "Could not find any news this time.";

}

function show_news() {
    return 'Hello';
}
