<?php
function newsajax_menu(){
    $items['path-to-ajax/%/%']= array(
        'access arguments'=> array('access content'),
        'page callback'=> 'newsajax_ajax_callback',
        'page arguments'=> array(1,2),
        'type'=> MENU_CALLBACK,
    );
    return $items;
}

function newsajax_ajax_callback($js, $node_id)
{
    $node = node_load($node_id);
    echo $node->field_image_url['und'][0]['value'];

    if($js == 'nojs'){
        drupal_goto('node/'. $node->nid);
    }
    $build = node_view($node);
    $html = render($build);
    $commands = array();
    $commands[]= ajax_command_html('#newsajax-ajax-wrapper', $html);
    print ajax_render($commands);
    exit;
}
